import React, { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { supabase } from "./supabase.js";

const ZONAS=["Metropolitana","Suroccidente","Suroriente","Riomar","Centro Histórico"];
const E={page:{minHeight:"100vh",background:"#f4f7fb",fontFamily:"Arial,sans-serif",color:"#172033"},header:{background:"white",padding:20,borderBottom:"1px solid #dbe2ea"},content:{maxWidth:1180,margin:"0 auto",padding:24},row:{display:"flex",gap:12,flexWrap:"wrap",alignItems:"center"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:18},card:{background:"white",border:"1px solid #dbe2ea",borderRadius:16,padding:20,boxShadow:"0 6px 18px rgba(15,23,42,.06)"},input:{width:"100%",boxSizing:"border-box",padding:11,marginTop:6,border:"1px solid #b9c4d2",borderRadius:10},btn:{border:0,borderRadius:10,padding:"11px 15px",cursor:"pointer",fontWeight:700},blue:{background:"#2563eb",color:"white"},white:{background:"white",border:"1px solid #b9c4d2",color:"#172033"},red:{background:"#fff1f2",border:"1px solid #fecdd3",color:"#be123c"},green:{background:"#ecfdf5",color:"#047857"},orange:{background:"#fff7ed",color:"#9a3412"},modalBg:{position:"fixed",inset:0,zIndex:20,background:"rgba(15,23,42,.55)",display:"flex",alignItems:"center",justifyContent:"center",padding:16},modal:{width:"100%",maxWidth:1000,maxHeight:"92vh",overflowY:"auto",background:"white",borderRadius:18,padding:24},block:{background:"#f8fafc",border:"1px solid #e2e8f0",borderRadius:12,padding:14},table:{width:"100%",borderCollapse:"collapse",minWidth:760},cell:{padding:11,borderBottom:"1px solid #e2e8f0",textAlign:"left"}};
const LV={nombre:"",zona:"",telefono:""};
const RV={tema:"",descripcion:"",fecha:"",lugar:"",personas_convocadas:"",personas_asistentes:"",entrego_premios:false,observaciones:""};
const norm=v=>String(v??"").trim();
const safe=v=>norm(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"_");
const fecha=f=>f?new Date(f+"T00:00:00").toLocaleDateString("es-CO",{day:"2-digit",month:"long",year:"numeric"}):"Sin fecha";

export default function App(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [leaders,setLeaders]=useState([]),[meetings,setMeetings]=useState([]),[attendance,setAttendance]=useState([]),[people,setPeople]=useState([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[kind,setKind]=useState("green");
 const [search,setSearch]=useState(""),[zoneFilter,setZoneFilter]=useState("Todas"),[rankingZone,setRankingZone]=useState("Metropolitana"),[year,setYear]=useState(new Date().getFullYear()),[modal,setModal]=useState(""),[leader,setLeader]=useState(null),[evidenceMeeting,setEvidenceMeeting]=useState(null),[evidence,setEvidence]=useState([]);
 const [strategy,setStrategy]=useState("reuniones");
 const [menuOpen,setMenuOpen]=useState(()=>window.innerWidth>768);
 const [cafeRecords,setCafeRecords]=useState(()=>JSON.parse(localStorage.getItem("cafeRecords")||"[]"));
 const [courseRecords,setCourseRecords]=useState(()=>JSON.parse(localStorage.getItem("courseRecords")||"[]"));
 const [lf,setLf]=useState(LV),[rf,setRf]=useState(RV),[excel,setExcel]=useState(null),[winners,setWinners]=useState(null),[photos,setPhotos]=useState([]),[excelRows,setExcelRows]=useState([]);
 const say=(t,k="green")=>{setMsg(t);setKind(k)};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load();else{setLeaders([]);setMeetings([]);setAttendance([]);setPeople([])}},[session]);
 async function load(){setLoading(true);const [a,b,c,d]=await Promise.all([supabase.from("lideres").select("*").order("nombre"),supabase.from("reuniones").select("*").order("fecha",{ascending:false}),supabase.from("asistencias").select("*"),supabase.from("personas").select("*")]);for(const x of [a,b,c,d])if(x.error)say(x.error.message,"red");setLeaders(a.data||[]);setMeetings(b.data||[]);setAttendance(c.data||[]);setPeople(d.data||[]);setLoading(false)}
 async function login(e){e.preventDefault();setSaving(true);const {error}=await supabase.auth.signInWithPassword({email,password});if(error)say(error.message,"red");setSaving(false)}
 async function saveLeader(e){e.preventDefault();setSaving(true);const {error}=await supabase.from("lideres").insert({...lf,estado:"Activo"});if(error)say(error.message,"red");else{setLf(LV);setModal("");say("Líder guardado");await load()}setSaving(false)}
 function openMeeting(l){setLeader(l);setRf(RV);setExcel(null);setWinners(null);setPhotos([]);setExcelRows([]);setMsg("");setModal("meeting")}
 async function readExcel(file){setExcel(file);if(!file){setExcelRows([]);return}try{const bytes=await file.arrayBuffer();const wb=XLSX.read(bytes,{type:"array"});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const all=rows.map(r=>({tipo_documento:norm(r.TipoDocumento||r.tipo_documento),numero_documento:norm(r.NumeroDocumento||r.numero_documento||r.Documento).replace(/\.0$/,""),nombre_completo:norm(r.NombreCompleto||r.nombre_completo||r.Nombre),telefono:norm(r.Telefono||r.telefono),zona:norm(r.Zona||r.zona)}));const invalid=all.filter(r=>r.numero_documento&&!/^\d{1,10}$/.test(r.numero_documento));const parsed=all.filter(r=>/^\d{1,10}$/.test(r.numero_documento)&&r.nombre_completo);setExcelRows(parsed);say(`Excel leído: ${parsed.length} asistentes válidos. ${invalid.length} documento(s) rechazado(s) por no ser numéricos o superar 10 dígitos.`,invalid.length?"orange":"green")}catch(err){setExcelRows([]);say("No se pudo leer el Excel: "+err.message,"red")}}
 async function upload(file,id,type){if(!file)return;const path=`${session.user.id}/${id}/${type}_${Date.now()}_${safe(file.name)}`;const up=await supabase.storage.from("evidencias-reuniones").upload(path,file);if(up.error)throw up.error;const rec=await supabase.from("evidencias").insert({reunion_id:id,tipo:type,nombre_archivo:file.name,ruta_archivo:path});if(rec.error)throw rec.error}
 async function importAttendance(rows,meetingId){const unique=[...new Map(rows.map(r=>[r.numero_documento,r])).values()];for(const p of unique){const {data,error}=await supabase.from("personas").upsert(p,{onConflict:"numero_documento"}).select("id").single();if(error)throw error;const a=await supabase.from("asistencias").upsert({persona_id:data.id,reunion_id:meetingId},{onConflict:"persona_id,reunion_id"});if(a.error)throw a.error}}
 async function saveMeeting(e){e.preventDefault();if(+rf.personas_asistentes>+rf.personas_convocadas)return say("Asistentes no puede superar convocados","red");if(excel&&excelRows.length===0)return say("El Excel no tiene columnas válidas","red");if(excelRows.length&&excelRows.length!==+rf.personas_asistentes)return say(`El Excel contiene ${excelRows.length} personas únicas, pero registraste ${rf.personas_asistentes} asistentes. Corrige antes de guardar.`,"red");setSaving(true);const {data,error}=await supabase.from("reuniones").insert({...rf,lider_id:leader.id,personas_convocadas:+rf.personas_convocadas,personas_asistentes:+rf.personas_asistentes}).select().single();if(error){say(error.message,"red");setSaving(false);return}try{if(excelRows.length)await importAttendance(excelRows,data.id);await upload(excel,data.id,"LISTA_ASISTENTES");await upload(winners,data.id,"LISTA_PREMIADOS");for(const p of photos)await upload(p,data.id,"FOTOGRAFIA");say("Reunión, asistentes y evidencias guardados");setModal("");await load()}catch(err){say("Reunión creada, pero faltó procesar una evidencia: "+err.message,"orange");await load()}setSaving(false)}
 async function remove(table,id,text){if(!confirm(text))return;const {error}=await supabase.from(table).delete().eq("id",id);if(error)say(error.message,"red");else await load()}
 async function viewEvidence(m){const {data,error}=await supabase.from("evidencias").select("*").eq("reunion_id",m.id);if(error)return say(error.message,"red");const out=await Promise.all((data||[]).map(async x=>{const r=await supabase.storage.from("evidencias-reuniones").createSignedUrl(x.ruta_archivo,3600);return{...x,url:r.data?.signedUrl||""}}));setEvidenceMeeting(m);setEvidence(out);setModal("evidence")}
 const leaderMeetings=id=>meetings.filter(m=>m.lider_id===id&&+m.fecha.slice(0,4)===+year);
 const filtered=useMemo(()=>leaders.filter(l=>{
  const matchesSearch=`${l.nombre} ${l.zona} ${l.telefono}`.toLowerCase().includes(search.toLowerCase());
  const matchesZone=zoneFilter==="Todas"||norm(l.zona).toLowerCase()===zoneFilter.toLowerCase();
  return matchesSearch&&matchesZone
 }),[leaders,search,zoneFilter]);
 const zones=useMemo(()=>{const rows=ZONAS.map(z=>{const ids=new Set(leaders.filter(l=>norm(l.zona).toLowerCase()===z.toLowerCase()).map(l=>l.id));const ms=meetings.filter(m=>ids.has(m.lider_id)&&+m.fecha.slice(0,4)===+year);return{zona:z,lideres:ids.size,reuniones:ms.length,convocados:ms.reduce((s,m)=>s+m.personas_convocadas,0),asistentes:ms.reduce((s,m)=>s+m.personas_asistentes,0)}});const total=rows.reduce((s,r)=>s+r.asistentes,0);return rows.map(r=>({...r,asistencia:r.convocados?Math.round(r.asistentes/r.convocados*100):0,peso:total?Math.round(r.asistentes/total*100):0})).sort((a,b)=>b.asistentes-a.asistentes)},[leaders,meetings,year]);
 function leaderStats(id){const ms=leaderMeetings(id),ids=new Set(ms.map(m=>m.id)),as=attendance.filter(a=>ids.has(a.reunion_id)),counts={};as.forEach(a=>counts[a.persona_id]=(counts[a.persona_id]||0)+1);return{meetings:ms,conv:ms.reduce((s,m)=>s+m.personas_convocadas,0),att:ms.reduce((s,m)=>s+m.personas_asistentes,0),unique:Object.keys(counts).length,repeated:Object.values(counts).filter(n=>n>1).length,counts}}
 function frequencyRows(id){const st=leaderStats(id);return Object.entries(st.counts).map(([pid,n])=>{const p=people.find(x=>x.id===+pid)||{};return{...p,veces:n}}).sort((a,b)=>b.veces-a.veces)}
 function zoneLeaderRows(zone){return leaders.filter(l=>norm(l.zona).toLowerCase()===zone.toLowerCase()).map(l=>{const s=leaderStats(l.id);return{nombre:l.nombre,reuniones:s.meetings.length,convocados:s.conv,asistentes:s.att,noAsistieron:s.conv-s.att,asistencia:s.conv?Math.round(s.att/s.conv*100):0,unicas:s.unique,repetidas:s.repeated}}).sort((a,b)=>b.asistentes-a.asistentes||b.asistencia-a.asistencia)}
 function csvValue(value){const text=String(value??"").replace(/"/g,'""');return `"${text}"`}
 function downloadCsv(filename,headers,rows){const content="\ufeff"+[headers.map(csvValue).join(";")].concat(rows.map(row=>row.map(csvValue).join(";"))).join("\r\n");const url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
 function exportAll(){downloadCsv(`reuniones_${year}.csv`,["Líder","Zona","Teléfono","Reunión","Fecha","Lugar","Convocados","Asistentes","No asistieron","Asistencia %","Premios","Descripción","Observaciones"],meetings.filter(m=>+m.fecha.slice(0,4)===+year).map(m=>{const l=leaders.find(x=>x.id===m.lider_id)||{};return[l.nombre,l.zona,l.telefono,m.tema,m.fecha,m.lugar,m.personas_convocadas,m.personas_asistentes,m.personas_convocadas-m.personas_asistentes,m.personas_convocadas?Math.round(m.personas_asistentes/m.personas_convocadas*100):0,m.entrego_premios?"Sí":"No",m.descripcion,m.observaciones]}))}
 const notice=kind==="red"?E.red:kind==="orange"?E.orange:E.green;
 if(loading&&!session)return <main style={E.page}><div style={E.content}>Cargando...</div></main>;
 if(!session)return <main style={{...E.page,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><form style={{...E.card,width:"100%",maxWidth:430}} onSubmit={login}><h1>Seguimiento de Estrategias</h1>{msg&&<p style={{...E.block,...notice}}>{msg}</p>}<label>Correo<input required type="email" style={E.input} value={email} onChange={e=>setEmail(e.target.value)}/></label><br/><br/><label>Contraseña<input required type="password" style={E.input} value={password} onChange={e=>setPassword(e.target.value)}/></label><br/><br/><button style={{...E.btn,...E.blue,width:"100%"}}>{saving?"Ingresando...":"Iniciar sesión"}</button></form></main>;
 return <div className="app-shell" style={E.page}>
  <style>{RESPONSIVE_CSS}</style>
  <aside className={`app-sidebar ${menuOpen?"open":"closed"}`}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><h2 style={{margin:"0 0 6px"}}>Estrategias</h2><button aria-label="Plegar menú" title="Plegar menú" onClick={()=>setMenuOpen(false)} style={{...E.btn,background:"#1e293b",color:"white",padding:"8px 11px"}}>✕</button></div><p style={{margin:"0 0 22px",fontSize:13,color:"#cbd5e1"}}>Panel de seguimiento</p>
   {[["reuniones","Reuniones"],["cafe","Café a tu Barrio"],["cursos","Cursos"]].map(([id,label])=><button key={id} onClick={()=>setStrategy(id)} style={{...E.btn,width:"100%",marginBottom:10,textAlign:"left",background:strategy===id?"#2563eb":"#1e293b",color:"white"}}>{label}</button>)}
   <button onClick={()=>supabase.auth.signOut()} style={{...E.btn,width:"100%",marginTop:18,textAlign:"left",background:"transparent",border:"1px solid #475569",color:"white"}}>Cerrar sesión</button>
  </aside><div className="app-main">
  <button className="menu-toggle" aria-label="Abrir o cerrar menú" onClick={()=>setMenuOpen(v=>!v)}>☰</button>
  {strategy==="reuniones"&&<>
  <header style={E.header}><div style={{maxWidth:1180,margin:"0 auto",...E.row,justifyContent:"space-between"}}><div><h1 style={{margin:0}}>Seguimiento de Estrategias</h1><p style={{marginBottom:0,color:"#64748b"}}>Reuniones, asistencia, frecuencia y rendimiento</p></div><div style={E.row}><button style={{...E.btn,...E.blue}} onClick={()=>setModal("leader")}>+ Agregar líder</button><button style={{...E.btn,...E.white}} onClick={()=>setModal("zones")}>Rendimiento por zonas</button><button style={{...E.btn,...E.white}} onClick={()=>setModal("zoneLeaders")}>Líderes por zona</button><button style={{...E.btn,...E.white}} onClick={exportAll}>Descargar información</button></div></div></header>
  <main style={E.content}>{msg&&<p style={{...E.block,...notice}}>{msg}</p>}<div style={{...E.card,...E.row,marginBottom:20}}><input style={{...E.input,flex:1,marginTop:0,minWidth:220}} placeholder="Buscar líder" value={search} onChange={e=>setSearch(e.target.value)}/><select style={{...E.input,width:210,marginTop:0}} value={zoneFilter} onChange={e=>setZoneFilter(e.target.value)}><option value="Todas">Todas las zonas</option>{ZONAS.map(z=><option key={z} value={z}>{z}</option>)}</select><select style={{...E.input,width:130,marginTop:0}} value={year} onChange={e=>setYear(+e.target.value)}>{[2025,2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></div>{filtered.length===0&&<p style={E.block}>No hay líderes registrados en la zona seleccionada.</p>}<div style={E.grid}>{filtered.map(l=>{const st=leaderStats(l.id);return <section key={l.id} style={E.card}><h2>{l.nombre}</h2><p><b>Zona:</b> {l.zona}</p><p><b>Teléfono:</b> {l.telefono}</p><p><b>Reuniones:</b> {st.meetings.length}</p><div style={E.row}><button style={{...E.btn,...E.blue}} onClick={()=>openMeeting(l)}>Registrar reunión</button><button style={{...E.btn,...E.white}} onClick={()=>{setLeader(l);setModal("history")}}>Ver reuniones</button><button style={{...E.btn,...E.white}} onClick={()=>{setLeader(l);setModal("performance")}}>Rendimiento</button><button style={{...E.btn,...E.white}} onClick={()=>{setLeader(l);setModal("frequency")}}>Repetidos</button><button style={{...E.btn,...E.red}} onClick={()=>remove("lideres",l.id,"¿Eliminar líder?")}>Eliminar</button></div></section>})}</div></main>
  </>}
  {strategy==="cafe"&&<CafeModule leaders={leaders} records={cafeRecords} setRecords={setCafeRecords} downloadCsv={downloadCsv}/>}
  {strategy==="cursos"&&<CoursesModule leaders={leaders} records={courseRecords} setRecords={setCourseRecords} downloadCsv={downloadCsv}/>}
  {modal==="leader"&&<div style={E.modalBg}><form style={E.modal} onSubmit={saveLeader}><h2>Agregar líder</h2><label>Nombre *<input required style={E.input} value={lf.nombre} onChange={e=>setLf({...lf,nombre:e.target.value})}/></label><br/><br/><label>Zona *<select required style={E.input} value={lf.zona} onChange={e=>setLf({...lf,zona:e.target.value})}><option value="">Seleccione</option>{ZONAS.map(z=><option key={z}>{z}</option>)}</select></label><br/><br/><label>Teléfono<input style={E.input} value={lf.telefono} onChange={e=>setLf({...lf,telefono:e.target.value})}/></label><br/><br/><div style={E.row}><button type="button" style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cancelar</button><button style={{...E.btn,...E.blue}}>Guardar</button></div></form></div>}
  {modal==="meeting"&&leader&&<div style={E.modalBg}><form style={E.modal} onSubmit={saveMeeting}><h2>Registrar reunión y evidencias</h2><p><b>Líder:</b> {leader.nombre}</p>{msg&&<p style={{...E.block,...notice}}>{msg}</p>}<label>Tema *<input required style={E.input} value={rf.tema} onChange={e=>setRf({...rf,tema:e.target.value})}/></label><br/><br/><label>Descripción *<textarea required rows="3" style={E.input} value={rf.descripcion} onChange={e=>setRf({...rf,descripcion:e.target.value})}/></label><br/><br/><div style={E.row}><label style={{flex:1}}>Fecha *<input required type="date" style={E.input} value={rf.fecha} onChange={e=>setRf({...rf,fecha:e.target.value})}/></label><label style={{flex:1}}>Lugar<input style={E.input} value={rf.lugar} onChange={e=>setRf({...rf,lugar:e.target.value})}/></label></div><br/><div style={E.row}><label style={{flex:1}}>Convocados *<input required type="number" min="0" style={E.input} value={rf.personas_convocadas} onChange={e=>setRf({...rf,personas_convocadas:e.target.value})}/></label><label style={{flex:1}}>Asistentes *<input required type="number" min="0" style={E.input} value={rf.personas_asistentes} onChange={e=>setRf({...rf,personas_asistentes:e.target.value})}/></label></div><br/><div style={E.block}><b>Excel de asistentes</b><p>Columnas: TipoDocumento, NumeroDocumento, NombreCompleto, Telefono, Zona.</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>readExcel(e.target.files?.[0]||null)}/>{excel&&<p>{excel.name}: <b>{excelRows.length} personas válidas</b></p>}</div><br/><div style={E.block}><b>Fotografías</b><br/><input type="file" accept="image/*" multiple onChange={e=>setPhotos([...e.target.files])}/></div><br/><div style={E.block}><label><input type="checkbox" checked={rf.entrego_premios} onChange={e=>setRf({...rf,entrego_premios:e.target.checked})}/> Se entregaron premios</label>{rf.entrego_premios&&<div><p>Excel de premiados</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setWinners(e.target.files?.[0]||null)}/></div>}</div><br/><label>Observaciones<textarea rows="3" style={E.input} value={rf.observaciones} onChange={e=>setRf({...rf,observaciones:e.target.value})}/></label><br/><br/><div style={E.row}><button type="button" style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cancelar</button><button style={{...E.btn,...E.blue}} disabled={saving}>{saving?"Guardando...":"Guardar"}</button></div></form></div>}
  {modal==="zones"&&<div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><h2>Rendimiento por zonas</h2><div style={E.row}><button style={{...E.btn,...E.blue}} onClick={()=>downloadCsv(`rendimiento_zonas_${year}.csv`,["Zona","Líderes","Reuniones","Convocados","Asistentes","Asistencia %","Peso %"],zones.map(z=>[z.zona,z.lideres,z.reuniones,z.convocados,z.asistentes,z.asistencia,z.peso]))}>Descargar</button><button style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cerrar</button></div></div><Table headers={["Zona","Líderes","Reuniones","Convocados","Asistentes","Asistencia","Peso"]} rows={zones.map(z=>[z.zona,z.lideres,z.reuniones,z.convocados,z.asistentes,z.asistencia+"%",z.peso+"%"])}/></div></div>}
  {modal==="zoneLeaders"&&<div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><div><h2 style={{marginBottom:4}}>Rendimiento de líderes por zona</h2><p style={{marginTop:0,color:"#64748b"}}>Comparación correspondiente a {year}</p></div><div style={E.row}><button style={{...E.btn,...E.blue}} onClick={()=>downloadCsv(`lideres_${rankingZone}_${year}.csv`,["Posición","Líder","Reuniones","Convocados","Asistentes","No asistieron","Asistencia %","Personas únicas","Repetidas"],zoneLeaderRows(rankingZone).map((r,i)=>[i+1,r.nombre,r.reuniones,r.convocados,r.asistentes,r.noAsistieron,r.asistencia,r.unicas,r.repetidas]))}>Descargar</button><button style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cerrar</button></div></div><div style={{...E.block,...E.row,marginBottom:18}}><label style={{minWidth:280}}><b>Seleccione una zona</b><select style={E.input} value={rankingZone} onChange={e=>setRankingZone(e.target.value)}>{ZONAS.map(z=><option key={z} value={z}>{z}</option>)}</select></label></div>{zoneLeaderRows(rankingZone).length>0?<><div style={{...E.block,...E.green,marginBottom:16}}><b>Líder con mayor asistencia:</b> {zoneLeaderRows(rankingZone)[0].nombre}, con {zoneLeaderRows(rankingZone)[0].asistentes} asistentes registrados.</div><Table headers={["Posición","Líder","Reuniones","Convocados","Asistentes","No asistieron","Asistencia","Personas únicas","Repetidas"]} rows={zoneLeaderRows(rankingZone).map((r,i)=>[i+1,r.nombre,r.reuniones,r.convocados,r.asistentes,r.noAsistieron,r.asistencia+"%",r.unicas,r.repetidas])}/></>:<p style={E.block}>No hay líderes registrados en {rankingZone}.</p>}<p style={{fontSize:13,color:"#64748b",marginTop:16}}>La clasificación se ordena por asistentes acumulados y, en caso de empate, por porcentaje de asistencia. Personas únicas y repetidas dependen de los Excel importados.</p></div></div>}
  {modal==="performance"&&leader&&(()=>{const s=leaderStats(leader.id);return <div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><h2>Rendimiento de {leader.nombre}</h2><button style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cerrar</button></div><div style={E.grid}>{[["Reuniones",s.meetings.length],["Convocados",s.conv],["Asistentes",s.att],["No asistieron",s.conv-s.att],["Asistencia",(s.conv?Math.round(s.att/s.conv*100):0)+"%"],["Personas únicas",s.unique],["Personas repetidas",s.repeated]].map(([a,b])=><div key={a} style={E.block}><small>{a}</small><h2>{b}</h2></div>)}</div><h3>Rendimiento por reunión</h3><Table headers={["Reunión","Fecha","Convocados","Asistentes","No asistieron","Asistencia"]} rows={s.meetings.map(m=>[m.tema,fecha(m.fecha),m.personas_convocadas,m.personas_asistentes,m.personas_convocadas-m.personas_asistentes,(m.personas_convocadas?Math.round(m.personas_asistentes/m.personas_convocadas*100):0)+"%"])}/></div></div>})()}
  {modal==="frequency"&&leader&&<div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><h2>Frecuencia de asistentes: {leader.nombre}</h2><div style={E.row}><button style={{...E.btn,...E.blue}} onClick={()=>downloadCsv(`frecuencia_${safe(leader.nombre)}_${year}.csv`,["Documento","Nombre","Teléfono","Veces que asistió"],frequencyRows(leader.id).map(p=>[p.numero_documento,p.nombre_completo,p.telefono,p.veces]))}>Descargar</button><button style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cerrar</button></div></div><p>Solo aparecen personas importadas desde Excel con número de documento.</p><Table headers={["Documento","Nombre","Teléfono","Veces que asistió"]} rows={frequencyRows(leader.id).map(p=>[p.numero_documento,p.nombre_completo,p.telefono,p.veces])}/></div></div>}
  {modal==="history"&&leader&&<div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><h2>Reuniones de {leader.nombre}</h2><button style={{...E.btn,...E.white}} onClick={()=>setModal("")}>Cerrar</button></div>{leaderMeetings(leader.id).map(m=><article key={m.id} style={{...E.card,marginBottom:14}}><h3>{m.tema}</h3><p>{fecha(m.fecha)} | {m.lugar}</p><p>{m.descripcion}</p><p><b>Convocados:</b> {m.personas_convocadas} | <b>Asistentes:</b> {m.personas_asistentes} | <b>Asistencia:</b> {m.personas_convocadas?Math.round(m.personas_asistentes/m.personas_convocadas*100):0}%</p><div style={E.row}><button style={{...E.btn,...E.white}} onClick={()=>viewEvidence(m)}>Evidencias</button><button style={{...E.btn,...E.red}} onClick={()=>remove("reuniones",m.id,"¿Eliminar reunión?")}>Eliminar</button></div></article>)}</div></div>}
  <button className="scroll-top" aria-label="Subir al principio" title="Subir al principio" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>↑</button>
  {modal==="evidence"&&<div style={E.modalBg}><div style={E.modal}><div style={{...E.row,justifyContent:"space-between"}}><h2>Evidencias: {evidenceMeeting?.tema}</h2><button style={{...E.btn,...E.white}} onClick={()=>setModal("history")}>Regresar</button></div>{evidence.map(x=><div key={x.id} style={{...E.block,marginBottom:10}}><b>{x.tipo}</b><p>{x.nombre_archivo}</p>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Abrir o descargar</a>}</div>)}</div></div>}
  </div>
 </div>
}
const RESPONSIVE_CSS=`
*{box-sizing:border-box} body{margin:0;overflow-x:hidden} .app-shell{display:flex;align-items:stretch}.app-sidebar{width:260px;min-width:260px;min-height:100vh;background:#0f172a;color:white;padding:20px;position:sticky;top:0;align-self:flex-start;transition:transform .25s ease,width .25s ease,min-width .25s ease;z-index:40}.app-sidebar.closed{width:0;min-width:0;padding:0;overflow:hidden;transform:translateX(-100%)}.app-main{flex:1;min-width:0;position:relative}.menu-toggle{position:fixed;left:14px;top:14px;z-index:45;border:0;border-radius:10px;background:#2563eb;color:white;width:44px;height:44px;font-size:22px;cursor:pointer;box-shadow:0 4px 14px rgba(0,0,0,.2)}.scroll-top{position:fixed;right:18px;bottom:18px;z-index:60;width:48px;height:48px;border:0;border-radius:50%;background:#2563eb;color:white;font-size:28px;font-weight:bold;cursor:pointer;box-shadow:0 5px 18px rgba(15,23,42,.3)}.module-title{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.module-title h1{margin-bottom:4px}
@media(max-width:768px){.app-sidebar{position:fixed;left:0;top:0;height:100vh;overflow-y:auto;box-shadow:8px 0 24px rgba(0,0,0,.28)}.app-sidebar.closed{width:260px;min-width:260px;padding:20px;transform:translateX(-110%)}.app-main{width:100%}header>div{padding-top:48px}main{padding:16px!important}h1{font-size:1.65rem;line-height:1.15}h2{font-size:1.25rem}input,select,textarea,button{max-width:100%}label{min-width:100%!important;width:100%}.module-title{align-items:stretch}.module-title button{width:100%}.menu-toggle{left:10px;top:10px}.scroll-top{right:12px;bottom:12px}}
@media(min-width:769px){.app-sidebar.open~.app-main .menu-toggle{left:274px}}
`;
function Field({label,children}){return <label style={{display:"block",flex:1,minWidth:220}}><b>{label}</b>{children}</label>}
function leaderData(leaders,id){return leaders.find(l=>String(l.id)===String(id))||{}}
function CafeModule({leaders,records,setRecords,downloadCsv}){
 const initial={lider_id:"",lider_nombre:"",zona:"",fecha:"",barrio:"",convocados:"",asistentes:"",descripcion:"",fotos:[]}; const [form,setForm]=useState(initial);
 function chooseLeader(id){const l=leaderData(leaders,id);setForm({...form,lider_id:id,lider_nombre:l.nombre||"",zona:l.zona||""})}
 function save(e){e.preventDefault();if(+form.asistentes>+form.convocados)return alert("Los asistentes no pueden superar a los convocados.");const next=[{...form,id:Date.now(),fotos:form.fotos.map(f=>f.name)},...records];setRecords(next);localStorage.setItem("cafeRecords",JSON.stringify(next));setForm(initial)}
 function removeRecord(id){const next=records.filter(r=>r.id!==id);setRecords(next);localStorage.setItem("cafeRecords",JSON.stringify(next))}
 return <main style={E.content}><div className="module-title"><div><h1>Café a tu Barrio</h1><p style={{color:"#64748b"}}>Registro y seguimiento de actividades por líder y zona.</p></div><button style={{...E.btn,...E.blue}} onClick={()=>downloadCsv("cafe_a_tu_barrio.csv",["Líder","Zona","Fecha","Barrio","Convocados","Asistentes","Descripción","Fotografías"],records.map(r=>[r.lider_nombre,r.zona,r.fecha,r.barrio,r.convocados,r.asistentes,r.descripcion,r.fotos?.length||0]))}>Descargar información</button></div><form style={{...E.card,marginBottom:20}} onSubmit={save}><div style={E.row}><Field label="Líder responsable *"><select required style={E.input} value={form.lider_id} onChange={e=>chooseLeader(e.target.value)}><option value="">Seleccione un líder</option>{leaders.map(l=><option key={l.id} value={l.id}>{l.nombre}</option>)}</select></Field><Field label="Zona"><input readOnly style={{...E.input,background:"#f1f5f9"}} value={form.zona} placeholder="Se completa al elegir el líder"/></Field></div><br/><div style={E.row}><Field label="Fecha *"><input required type="date" style={E.input} value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></Field><Field label="Barrio *"><input required style={E.input} value={form.barrio} onChange={e=>setForm({...form,barrio:e.target.value})}/></Field></div><br/><div style={E.row}><Field label="Personas convocadas *"><input required min="0" type="number" style={E.input} value={form.convocados} onChange={e=>setForm({...form,convocados:e.target.value})}/></Field><Field label="Personas asistentes *"><input required min="0" type="number" style={E.input} value={form.asistentes} onChange={e=>setForm({...form,asistentes:e.target.value})}/></Field></div><br/><Field label="Descripción de la actividad *"><textarea required rows="4" style={E.input} value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></Field><br/><Field label="Registro fotográfico"><input type="file" accept="image/*" multiple style={E.input} onChange={e=>setForm({...form,fotos:[...e.target.files]})}/></Field><br/><button style={{...E.btn,...E.blue}}>Guardar actividad</button></form><h2>Actividades registradas</h2><div style={E.grid}>{records.length?records.map(r=><article key={r.id} style={E.card}><h3>{r.barrio}</h3><p><b>Líder:</b> {r.lider_nombre}</p><p><b>Zona:</b> {r.zona}</p><p><b>Fecha:</b> {fecha(r.fecha)}</p><p><b>Convocados:</b> {r.convocados} | <b>Asistentes:</b> {r.asistentes}</p><p>{r.descripcion}</p><p><b>Fotografías:</b> {r.fotos?.length||0}</p><button style={{...E.btn,...E.red}} onClick={()=>removeRecord(r.id)}>Eliminar</button></article>):<p style={E.block}>No hay actividades registradas.</p>}</div></main>
}
function CoursesModule({leaders,records,setRecords,downloadCsv}){
 const initial={lider_id:"",lider_nombre:"",zona:"",nombre:"",fecha:"",lugar:"",instructor:"",participantes:"",asistentes:"",lista:[],duplicadosCurso:0,evidencias:[],certificados:[]};
 const [form,setForm]=useState(initial),[leaderFilter,setLeaderFilter]=useState("Todos");
 function chooseLeader(id){const l=leaderData(leaders,id);setForm({...form,lider_id:id,lider_nombre:l.nombre||"",zona:l.zona||""})}
 async function readCourseExcel(file){if(!file)return setForm({...form,lista:[],duplicadosCurso:0});try{const bytes=await file.arrayBuffer(),wb=XLSX.read(bytes,{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const all=rows.map(r=>({documento:norm(r.NumeroDocumento||r.numero_documento||r.Documento||r.documento).replace(/\.0$/,""),nombre:norm(r.NombreCompleto||r.nombre_completo||r.Nombre||r.nombre),telefono:norm(r.Telefono||r.telefono)}));const invalid=all.filter(r=>r.documento&&!/^\d{1,10}$/.test(r.documento));const parsed=all.filter(r=>/^\d{1,10}$/.test(r.documento)&&r.nombre);const seen=new Set(),unique=[],duplicates=[];parsed.forEach(r=>{if(seen.has(r.documento))duplicates.push(r);else{seen.add(r.documento);unique.push(r)}});setForm({...form,lista:unique,duplicadosCurso:duplicates.length,asistentes:String(unique.length)});alert(`Excel leído: ${unique.length} personas únicas, ${duplicates.length} repetidas y ${invalid.length} documento(s) rechazado(s) por superar 10 dígitos o contener caracteres no numéricos.`)}catch(err){alert("No se pudo leer el Excel: "+err.message)}}
 function save(e){e.preventDefault();if(+form.asistentes>+form.participantes)return alert("La asistencia no puede superar a los participantes.");if(!form.lista.length)return alert("Carga el Excel con la lista de asistentes para calcular beneficiarios y repetidos.");if(form.lista.length!==+form.asistentes)return alert(`El Excel tiene ${form.lista.length} personas únicas y el campo asistentes indica ${form.asistentes}.`);const next=[{...form,id:Date.now(),evidencias:form.evidencias.map(f=>f.name),certificados:form.certificados.map(f=>f.name)},...records];setRecords(next);localStorage.setItem("courseRecords",JSON.stringify(next));setForm(initial)}
 function removeRecord(id){const next=records.filter(r=>r.id!==id);setRecords(next);localStorage.setItem("courseRecords",JSON.stringify(next))}
 function statsForLeader(id){const courses=records.filter(r=>String(r.lider_id)===String(id)),counts={};courses.forEach(c=>(c.lista||[]).forEach(person=>counts[person.documento]=(counts[person.documento]||0)+1));return{courses,total:courses.reduce((a,c)=>a+(c.lista?.length||+c.asistentes||0),0),unique:Object.keys(counts).length,repeated:Object.values(counts).filter(n=>n>1).length,counts}}
 function repeatedInCourse(course){const st=statsForLeader(course.lider_id);return (course.lista||[]).filter(p=>(st.counts[p.documento]||0)>1)}
 const summaryLeaders=leaders.map(l=>({leader:l,stats:statsForLeader(l.id)})).filter(x=>x.stats.courses.length);
 const visible=leaderFilter==="Todos"?records:records.filter(r=>String(r.lider_id)===leaderFilter);
 return <main style={E.content}><div className="module-title"><div><h1>Cursos</h1><p style={{color:"#64748b"}}>Conteo de personas beneficiadas, beneficiarios únicos y personas que han participado en más de un curso del mismo líder.</p></div><button style={{...E.btn,...E.blue}} onClick={()=>downloadCsv("cursos.csv",["Líder","Zona","Curso","Fecha","Lugar","Instructor","Inscritos","Beneficiarios únicos","Repetidos","Evidencias","Certificados"],records.map(r=>[r.lider_nombre,r.zona,r.nombre,r.fecha,r.lugar,r.instructor,r.participantes,r.lista?.length||r.asistentes,repeatedInCourse(r).length,r.evidencias?.length||0,r.certificados?.length||0]))}>Descargar información</button></div>
 <section style={{...E.card,marginBottom:20}}><div style={{...E.row,justifyContent:"space-between"}}><h2 style={{margin:0}}>Resumen general por líder</h2><button style={{...E.btn,...E.white}} onClick={()=>downloadCsv("resumen_cursos_por_lider.csv",["Líder","Zona","Cursos","Participaciones","Beneficiarios únicos","Personas repetidas"],summaryLeaders.map(x=>[x.leader.nombre,x.leader.zona,x.stats.courses.length,x.stats.total,x.stats.unique,x.stats.repeated]))}>Descargar resumen</button><select style={{...E.input,width:260,marginTop:0}} value={leaderFilter} onChange={e=>setLeaderFilter(e.target.value)}><option value="Todos">Todos los líderes</option>{leaders.map(l=><option key={l.id} value={String(l.id)}>{l.nombre}</option>)}</select></div><br/><Table headers={["Líder","Zona","Cursos","Participaciones","Beneficiarios únicos","Personas repetidas"]} rows={summaryLeaders.map(x=>[x.leader.nombre,x.leader.zona,x.stats.courses.length,x.stats.total,x.stats.unique,x.stats.repeated])}/><p style={{fontSize:13,color:"#64748b"}}>Participaciones suma todas las asistencias. Beneficiarios únicos cuenta cada documento una sola vez. Personas repetidas identifica documentos presentes en dos o más cursos del mismo líder.</p></section>
 <form style={{...E.card,marginBottom:20}} onSubmit={save}><h2>Registrar curso</h2><div style={E.row}><Field label="Líder responsable *"><select required style={E.input} value={form.lider_id} onChange={e=>chooseLeader(e.target.value)}><option value="">Seleccione un líder</option>{leaders.map(l=><option key={l.id} value={l.id}>{l.nombre}</option>)}</select></Field><Field label="Zona"><input readOnly style={{...E.input,background:"#f1f5f9"}} value={form.zona} placeholder="Se completa al elegir el líder"/></Field></div><br/><Field label="Nombre del curso *"><input required style={E.input} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><br/><div style={E.row}><Field label="Fecha *"><input required type="date" style={E.input} value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></Field><Field label="Lugar *"><input required style={E.input} value={form.lugar} onChange={e=>setForm({...form,lugar:e.target.value})}/></Field><Field label="Instructor *"><input required style={E.input} value={form.instructor} onChange={e=>setForm({...form,instructor:e.target.value})}/></Field></div><br/><div style={E.row}><Field label="Participantes inscritos *"><input required min="0" type="number" style={E.input} value={form.participantes} onChange={e=>setForm({...form,participantes:e.target.value})}/></Field><Field label="Asistentes únicos"><input readOnly type="number" style={{...E.input,background:"#f1f5f9"}} value={form.asistentes}/></Field></div><br/><div style={E.block}><b>Excel de asistentes *</b><p>Columnas aceptadas: NumeroDocumento, NombreCompleto y Telefono. El documento permite detectar personas repetidas.</p><input required type="file" accept=".xlsx,.xls,.csv" onChange={e=>readCourseExcel(e.target.files?.[0]||null)}/>{form.lista.length>0&&<p><b>{form.lista.length}</b> asistentes únicos. Repetidos dentro del archivo: <b>{form.duplicadosCurso}</b>.</p>}</div><br/><div style={E.row}><Field label="Evidencias"><input type="file" multiple style={E.input} onChange={e=>setForm({...form,evidencias:[...e.target.files]})}/></Field><Field label="Certificados"><input type="file" multiple accept=".pdf,image/*" style={E.input} onChange={e=>setForm({...form,certificados:[...e.target.files]})}/></Field></div><br/><button style={{...E.btn,...E.blue}}>Guardar curso</button></form>
 <h2>Cursos registrados</h2><div style={E.grid}>{visible.length?visible.map(r=>{const repeated=repeatedInCourse(r);return <article key={r.id} style={E.card}><h3>{r.nombre}</h3><p><b>Líder:</b> {r.lider_nombre}</p><p><b>Zona:</b> {r.zona}</p><p><b>Fecha:</b> {fecha(r.fecha)} | <b>Lugar:</b> {r.lugar}</p><p><b>Instructor:</b> {r.instructor}</p><p><b>Inscritos:</b> {r.participantes} | <b>Beneficiarios únicos del curso:</b> {r.lista?.length||r.asistentes}</p><p><b>Repetidos en otros cursos del líder:</b> {repeated.length}</p>{repeated.length>0&&<details><summary>Ver personas repetidas</summary><ul>{repeated.map(p=><li key={p.documento}>{p.nombre} | {p.documento}</li>)}</ul></details>}<p><b>Duplicados en el Excel:</b> {r.duplicadosCurso||0}</p><p><b>Evidencias:</b> {r.evidencias?.length||0} | <b>Certificados:</b> {r.certificados?.length||0}</p><button style={{...E.btn,...E.red}} onClick={()=>removeRecord(r.id)}>Eliminar</button></article>}):<p style={E.block}>No hay cursos registrados.</p>}</div></main>
}
function Table({headers,rows}){return <div style={{overflowX:"auto"}}><table style={E.table}><thead><tr style={{background:"#eff6ff"}}>{headers.map(h=><th key={h} style={E.cell}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} style={E.cell}>{v}</td>)}</tr>):<tr><td colSpan={headers.length} style={E.cell}>Sin datos</td></tr>}</tbody></table></div>}
